name: "🤘 Publish NPM Package"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:nayx
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nayx-build
          path: dist
        
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@sabriayes'
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: nayx-build
      - name: Publish to NPM
        run: |
          cd nayx
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
