name: "🤘 Publish NPM Package"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: dependencies
        run: npm install
      - name: build
        run: ng build naylalabs
        
  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: publish
        run: |
          cd dist/naylalabs
          npm config set //registry.npmjs.org/:_authToken ${NPM_ACCESS_TOKEN}
          npm publish --ignore-scripts --access public
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
