name: "🤘 Publish NPM Package"

on:
  push:
    braches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:lib
        run: cp .npmrc dist/naylalabs/.npmrc
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ng-dist
          path: dist
        
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ng-dist
      - name: Publish to NPM
        run: |
          cd naylalabs
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
